<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Email Notification System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <style type="text/css">

        .text{
            margin-top: 0;
            color: #565656;
            font-family: Georgia,serif;font-size: 14px;
            line-height: 25px;
            margin-bottom: 25px
        }

        .logo{
            border: 0;
            -ms-interpolation-mode: bicubic;
            display: block;

            width: 250px;
            height: auto;
            margin-left: 70px;

        }

        .footer{
            font-family: Georgia,serif;font-size: 11px;
            margin-bottom: 1px;
            margin-top: 1px;
        }

    </style>

</head>
<body>


    <div id="emb-email-header">
        <img class="logo" src="http://www.lestroismarios.com/images/3marios_logo_v7.png" alt="L3M Logo">
    </div>

    <p class="text">A new comment has been posted, please visit <a href="http://www.lestroismarios.com/php/customer.php">lestroismarios.com</a> to review it.</p>

    <p class="footer">You received this notification because you are registered as a user in lestroismarios.com.
        To stop receiving these notification visit MYACCOUNT and uncheck notify me by email of new comment posted.</p>

    <p class="footer">Please do not reply to this email which have been generated by our system. If you have questions regarding
        this email please do not hesitate to contact us to the information provided in our website under the section CONTACT.</p>


</body>
</html>